msm8916-common/Android.mk
msm8916-common/proprietary/bin/ims_rtp_daemon
msm8916-common/proprietary/bin/imscmservice
msm8916-common/proprietary/bin/imsdatadaemon
msm8916-common/proprietary/bin/imsqmidaemon
msm8916-common/proprietary/bin/imsrcsd
msm8916-common/proprietary/etc/permissions/imscm.xml
msm8916-common/proprietary/etc/permissions/qti-vzw-ims-internal.xml
msm8916-common/proprietary/vendor/app/ims/ims.apk
msm8916-common/proprietary/vendor/app/imssettings/imssettings.apk
msm8916-common/proprietary/vendor/lib/com.qualcomm.qti.imscmservice@1.0.so
msm8916-common/proprietary/vendor/lib/lib-dplmedia.so
msm8916-common/proprietary/vendor/lib/lib-ims-rcscmjni.so
msm8916-common/proprietary/vendor/lib/lib-imsSDP.so
msm8916-common/proprietary/vendor/lib/lib-imscamera.so
msm8916-common/proprietary/vendor/lib/lib-imsdpl.so
msm8916-common/proprietary/vendor/lib/lib-imsqimf.so
msm8916-common/proprietary/vendor/lib/lib-imsrcs.so
msm8916-common/proprietary/vendor/lib/lib-imsrcscm.so
msm8916-common/proprietary/vendor/lib/lib-imsrcscmclient.so
msm8916-common/proprietary/vendor/lib/lib-imsrcscmservice.so
msm8916-common/proprietary/vendor/lib/lib-imss.so
msm8916-common/proprietary/vendor/lib/lib-imsvideocodec.so
msm8916-common/proprietary/vendor/lib/lib-imsvt.so
msm8916-common/proprietary/vendor/lib/lib-imsvtextutils.so
msm8916-common/proprietary/vendor/lib/lib-imsvtutils.so
msm8916-common/proprietary/vendor/lib/lib-imsxml.so
msm8916-common/proprietary/vendor/lib/lib-rcsimssjni.so
msm8916-common/proprietary/vendor/lib/lib-rcsjni.so
msm8916-common/proprietary/vendor/lib/lib-rtpcommon.so
msm8916-common/proprietary/vendor/lib/lib-rtpcore.so
msm8916-common/proprietary/vendor/lib/lib-rtpdaemoninterface.so
msm8916-common/proprietary/vendor/lib/lib-rtpsl.so
msm8916-common/proprietary/vendor/lib/libimscamera_jni.so
msm8916-common/proprietary/vendor/lib/libimsmedia_jni.so
msm8916-common/proprietary/vendor/lib/librcc.so
msm8916-common/proprietary/vendor/lib/vendor.qti.imsrtpservice@1.0.so
